apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac
  labels:
    app: tictac
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tictac
  template:
    metadata:
      labels:
        app: tictac
    spec:
      containers:
        - name: tictac
          image: ravi4763/tictak:replaceImageTag
          ports:
            - containerPort: 80
